# Site settings
title: Alex Martinez
email: alex@istrategylabs.com
description: > # this means to ignore newlines until "baseurl:"
  I’m Alex Martinez, a web designer and front-end developer in Washington, DC. Currently, I work at an awesome company, ISL, where I focus on product and user experience design. I also work as a front-end developer.
When I’m not computer-ing, a lot of my time is spent running, doing yoga, playing fifa.
I love to run, fly, travel, learn, teach, and just do awesome things.
This site was built using Jekyll and is hosted on Github.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: alx_mrtnz
github_username:  alxmrtnz
linkedin_username: alxmrtnz
facebook_username: alexandermiguelmartinez
dribbble_username: alxmrtnz


# Build settings
markdown: kramdown

# this goes inside _config.yml. Change as required
navigation:
- text: Thoughts
  url: /thoughts
- text: About
  url: /about